[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ag2[gemini,openai]>=0.10.2",
    "fastapi[standard]>=0.125.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "websocket>=0.2.1",
]
